name: Run Tests

on:
  pull_request:
    branches:
      - "main"

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@latest
      - name: Install Node.js v20
        uses: actions/setup-node@latest
        with:
          node-version: 20
      - name: Install PNPM
        uses: pnpm/action-setup@latest
      - name: Install dependencies
        run: pnpm install
      - name: Build tfvm package
        run: pnpm build
      - name: Link and test tfvm
        run: pnpm link .dist && pnpm test
